### ISSUE TITLE
Stop working?

### ISSUE THREAD

**Issue by eitsupi** [nx10/cransubs-server#1]
I don't know if it has something to do with CRAN being out of service a few days ago, but it looks like cransubs data is no longer being updated.
Currently, it seems that data from 7 days ago is still being displayed.

**Comment by nx10** [comment]
Thanks for pinging me. Should be fixed now! The issue was that the CRAN servers responded with ambiguous local timestamps due to daylight savings time in Vienna where their servers are based.
We now just use the older timestamp in that case (f4b5c95)

**Comment by eitsupi** [comment]
Thanks for quick update!
